# Generated by Django 6.0.1 on 2026-01-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='follow_up_cadence_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
