# Generated by Django 6.0.1 on 2026-01-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_person_follow_up_cadence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
