# Generated by Django 6.0.1 on 2026-01-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_person_created_at_person_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.person')),
                ('interaction_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.interactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.orgtype')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipOrganizationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.person')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipPersonPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_outgoing', to='network.person')),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_incoming', to='network.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('person_1', models.F('person_2')), _negated=True), name='no_self_relationship'), models.CheckConstraint(condition=models.Q(('person_1__lt', models.F('person_2'))), name='enforce_person_ordering'), models.UniqueConstraint(fields=('person_1', 'person_2'), name='unique_person_relationship')],
            },
        ),
    ]
