# Generated by Django 6.0.1 on 2026-01-11 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_interactiontype_orgtype_interaction_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['person', '-date', '-id'], name='network_int_person__aba2d2_idx'),
        ),
    ]
