# Generated by Django 6.0.1 on 2026-01-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_interaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
