# Generated by Django 6.0.1 on 2026-01-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_organization_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='follow_up_cadence_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_person_name'),
        ),
    ]
