# Generated by Django 6.0.1 on 2026-01-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_person_follow_up_cadence_days_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_org_name'),
        ),
    ]
