# Generated by Django 6.0.2 on 2026-02-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_organization_unique_org_name'),
        ('tasks', '0005_task_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name', 'id'], name='network_per_last_na_c4ef24_idx'),
        ),
        migrations.AddField(
            model_name='interactiontask',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='network.interaction'),
        ),
        migrations.AddField(
            model_name='interactiontask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_links', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='network.organization'),
        ),
        migrations.AddField(
            model_name='taskorganization',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='network.person'),
        ),
        migrations.AddField(
            model_name='taskperson',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='interactiontask',
            constraint=models.UniqueConstraint(fields=('interaction', 'task'), name='unique_interaction_task_link'),
        ),
        migrations.AddConstraint(
            model_name='taskorganization',
            constraint=models.UniqueConstraint(fields=('task', 'organization'), name='unique_task_organization_link'),
        ),
        migrations.AddConstraint(
            model_name='taskperson',
            constraint=models.UniqueConstraint(fields=('task', 'person'), name='unique_task_person_link'),
        ),
    ]
