# Generated by Django 6.0.2 on 2026-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_interactiontask_taskorganization_taskperson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
