# Generated by Django 6.0.2 on 2026-02-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_person_email_person_linkedin_url"),
        ("tasks", "0007_projectlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("interested", "Interested"),
                            ("committed", "Committed"),
                            ("fulfilled", "Fulfilled"),
                            ("unfulfilled", "Unfulfilled"),
                        ],
                        default="prospect",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="network.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="network.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_links",
                        to="network.lead",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_links",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["-updated_at"], name="network_lea_updated_a2bf21_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organization__isnull", True),
                    ("person__isnull", True),
                    _negated=True,
                ),
                name="lead_requires_person_or_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadtask",
            constraint=models.UniqueConstraint(
                fields=("lead", "task"), name="unique_lead_task_link"
            ),
        ),
    ]
