# Generated by Django 6.0.2 on 2026-02-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0012_lead_leadtask_lead_network_lea_updated_a2bf21_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="people",
            field=models.ManyToManyField(
                blank=True, related_name="interactions", to="network.person"
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.person",
            ),
        ),
    ]
