# Generated by Django 6.0.2 on 2026-02-27 12:08

from django.db import migrations


def copy_person_fk_to_m2m(apps, schema_editor):
    Interaction = apps.get_model("network", "Interaction")
    for interaction in Interaction.objects.filter(person__isnull=False):
        interaction.people.add(interaction.person_id)


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0013_add_interaction_people_m2m"),
    ]

    operations = [
        migrations.RunPython(copy_person_fk_to_m2m, migrations.RunPython.noop),
    ]
