# Generated by Django 6.0.2 on 2026-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0014_copy_person_fk_to_m2m"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="interaction",
            name="network_int_person__aba2d2_idx",
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["-date", "-id"], name="network_int_date_074ae8_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="person",
        ),
    ]
