# Generated by Django 6.0.2 on 2026-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0015_remove_interaction_person_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, related_name="interactions", to="network.organization"
            ),
        ),
    ]
