# Generated by Django 6.0.2 on 2026-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0017_interactionmedium_interaction_medium"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="people", to="network.persontag"
            ),
        ),
    ]
