# Generated by Django 6.0.2 on 2026-03-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0020_contact_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgOrgRelationshipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipOrganizationOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_relationships_outgoing",
                        to="network.organization",
                    ),
                ),
                (
                    "org_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_relationships_incoming",
                        to="network.organization",
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="network.orgorgrelationshiptype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("org_1", models.F("org_2")), _negated=True),
                        name="no_self_org_relationship",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("org_1__lt", models.F("org_2"))),
                        name="enforce_org_ordering",
                    ),
                    models.UniqueConstraint(
                        fields=("org_1", "org_2"), name="unique_org_relationship"
                    ),
                ],
            },
        ),
    ]
