# Generated by Django 6.0.2 on 2026-03-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0021_orgorgrelationshiptype_and_more"),
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionPageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_links",
                        to="network.interaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_links",
                        to="notebook.page",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interaction", "page"),
                        name="unique_interaction_page_link",
                    )
                ],
            },
        ),
    ]
