#!/usr/bin/env bash
# setup.sh — Provision a fresh Ubuntu VPS for the ToDo app
# Run as root: bash setup.sh
set -euo pipefail

APP_DIR="/opt/todoapp"
APP_USER="todoapp"
REPO_URL="https://github.com/maxachis/todo-app.git"
LITESTREAM_VERSION="0.3.13"
PYTHON_VERSION="3.13"

# ─── Helpers ───────────────────────────────────────────────────────────────────

info()  { echo -e "\n\033[1;34m==>\033[0m \033[1m$*\033[0m"; }
error() { echo -e "\n\033[1;31mERROR:\033[0m $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || error "This script must be run as root."

# ─── 1. System packages ───────────────────────────────────────────────────────

info "Updating system packages"
apt update && apt upgrade -y
apt install -y software-properties-common curl git ufw

# ─── 2. Python 3.13 (deadsnakes PPA) ──────────────────────────────────────────

info "Installing Python ${PYTHON_VERSION}"
add-apt-repository -y ppa:deadsnakes/ppa
apt update
apt install -y "python${PYTHON_VERSION}" "python${PYTHON_VERSION}-venv" "python${PYTHON_VERSION}-dev"

# ─── 3. Install Caddy ─────────────────────────────────────────────────────────

info "Installing Caddy"
apt install -y debian-keyring debian-archive-keyring apt-transport-https
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    | tee /etc/apt/sources.list.d/caddy-stable.list
apt update
apt install -y caddy

# ─── 4. Install Tailscale ─────────────────────────────────────────────────────

info "Installing Tailscale"
curl -fsSL https://tailscale.com/install.sh | sh

# ─── 5. Install Litestream ────────────────────────────────────────────────────

info "Installing Litestream v${LITESTREAM_VERSION}"
LITESTREAM_URL="https://github.com/benbjohnson/litestream/releases/download/v${LITESTREAM_VERSION}/litestream-v${LITESTREAM_VERSION}-linux-amd64.deb"
curl -fsSL -o /tmp/litestream.deb "${LITESTREAM_URL}"
dpkg -i /tmp/litestream.deb
rm /tmp/litestream.deb

# ─── 6. Create app user ───────────────────────────────────────────────────────

info "Creating system user: ${APP_USER}"
if ! id "${APP_USER}" &>/dev/null; then
    useradd --system --shell /usr/sbin/nologin --home-dir "${APP_DIR}" "${APP_USER}"
fi

# ─── 7. Clone repo ────────────────────────────────────────────────────────────

info "Cloning repository to ${APP_DIR}"
if [[ -d "${APP_DIR}/.git" ]]; then
    echo "Repo already exists, pulling latest changes"
    git -C "${APP_DIR}" pull
else
    git clone "${REPO_URL}" "${APP_DIR}"
fi
chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}"

# ─── 8. Python venv ───────────────────────────────────────────────────────────

info "Setting up Python virtual environment"
"python${PYTHON_VERSION}" -m venv "${APP_DIR}/venv"
"${APP_DIR}/venv/bin/pip" install --upgrade pip
"${APP_DIR}/venv/bin/pip" install django markdown bleach gunicorn

# ─── 9. Environment file ──────────────────────────────────────────────────────

info "Generating environment file"
if [[ ! -f "${APP_DIR}/.env" ]]; then
    SECRET_KEY=$("${APP_DIR}/venv/bin/python" -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())")
    cp "${APP_DIR}/deploy/.env.example" "${APP_DIR}/.env"
    sed -i "s|<auto-generated-during-setup>|${SECRET_KEY}|" "${APP_DIR}/.env"
    chown "${APP_USER}:${APP_USER}" "${APP_DIR}/.env"
    chmod 600 "${APP_DIR}/.env"
    echo ".env created with generated SECRET_KEY"
else
    echo ".env already exists, skipping"
fi

# ─── 10. Django setup ─────────────────────────────────────────────────────────

info "Running Django migrations and collectstatic"
sudo -u "${APP_USER}" bash -c "
    set -a
    source ${APP_DIR}/.env
    set +a
    ${APP_DIR}/venv/bin/python ${APP_DIR}/manage.py migrate --noinput
    ${APP_DIR}/venv/bin/python ${APP_DIR}/manage.py collectstatic --noinput
"

# ─── 11. Install config files ─────────────────────────────────────────────────

info "Installing config files"
cp "${APP_DIR}/deploy/Caddyfile" /etc/caddy/Caddyfile
cp "${APP_DIR}/deploy/todoapp.service" /etc/systemd/system/todoapp.service
cp "${APP_DIR}/deploy/litestream.yml" /etc/litestream.yml
cp "${APP_DIR}/deploy/litestream.service" /etc/systemd/system/litestream.service
systemctl daemon-reload

# ─── 12. Firewall (UFW) ───────────────────────────────────────────────────────

info "Configuring firewall"
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp        # SSH
ufw allow 41641/udp     # Tailscale
ufw --force enable

# ─── 13. Enable and start services ────────────────────────────────────────────

info "Enabling and starting services"
systemctl enable --now litestream
systemctl enable --now todoapp
systemctl enable --now caddy

# ─── 14. Done ──────────────────────────────────────────────────────────────────

info "Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Run 'tailscale up' to join your tailnet"
echo "  2. Get your Tailscale hostname: tailscale status"
echo "  3. Generate Tailscale HTTPS certs: tailscale cert <hostname>"
echo "  4. Update ALLOWED_HOSTS in /opt/todoapp/.env with your Tailscale hostname"
echo "  5. Set TAILSCALE_HOSTNAME env var for Caddy (e.g. in /etc/caddy/environment)"
echo "  6. Configure R2 credentials in /opt/todoapp/.env for Litestream backups"
echo "  7. Restart services: systemctl restart litestream todoapp caddy"
echo ""
