# Generated by Django 6.0.2 on 2026-02-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom_dates', 'Custom Dates')], default='none', max_length=20),
        ),
    ]
