# Generated by Django 6.0.2 on 2026-03-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_list_is_system_inbox"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="priority",
        ),
    ]
