# Generated by Django 6.0.2 on 2026-02-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField(blank=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("wiki", "Wiki")],
                        default="wiki",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-updated_at"], name="notebook_pa_updated_30cc49_idx"
                    ),
                    models.Index(
                        fields=["page_type", "-date"],
                        name="notebook_pa_page_ty_648b5f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PageEntityMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("task", "Task"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_mentions",
                        to="notebook.page",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="notebook_pa_entity__b5e611_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "entity_type", "entity_id"),
                        name="unique_page_entity_mention",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="notebook.page",
                    ),
                ),
                (
                    "target_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="notebook.page",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_page", "target_page"), name="unique_page_link"
                    )
                ],
            },
        ),
    ]
