# Generated by Django 6.0.2 on 2026-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageentitymention",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("organization", "Organization"),
                    ("task", "Task"),
                    ("project", "Project"),
                    ("interaction", "Interaction"),
                ],
                max_length=20,
            ),
        ),
    ]
